name: multimodal
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip=20.1.1
  - python=3.10
  - cudatoolkit=11.1
  - pip:
    - -r requirements_run.txt
    - -r requirements_test.txt
